### ISSUE TITLE
[Bug Report] Crash on startup

### ISSUE THREAD

**Issue by Royal-Jelly** [PyralIron/Advanced-TFC-Tech#1]
Crash Snippit:
java.lang.NoSuchMethodError: com.pyraliron.advancedtfctech.items.ItemBase.setUnlocalizedName(Ljava/lang/String;)Lnet/minecraft/item/Item;
    at com.pyraliron.advancedtfctech.items.ItemBase.<init>(ItemBase.java:16)
    at com.pyraliron.advancedtfctech.items.ItemPirn.<init>(ItemPirn.java:13)
    at com.pyraliron.advancedtfctech.init.ModItems.<clinit>(ModItems.java:17)
    at com.pyraliron.advancedtfctech.AdvancedTFCTech.<clinit>(AdvancedTFCTech.java:38)

[Full Logfile](https://pastebin.com/89NtkkQA)

**Comment by Royal-Jelly** [comment]
wow that was fast ~ thankies
